### ISSUE TITLE
VACs cannot fit anything in their "lightweight" slots

### ISSUE THREAD

**Issue by IsaacOstlund** [sweet-org/sweet#19] opened 2024-07-20 23:37 UTC
Not sure if this is related to the other drone/fighter problem, but in any VAC you cannot press an empty slot or the "fill all" button for the frigate/destroyers. trying to click those buttons does nothing.

**Comment by Blaumeise03** [comment] 2024-07-21 07:36
Yes, thats also because of the market groups issue and already fixed in the commit I pushed for the other issue.

Duplicate of #17

**Comment by Blaumeise03** [comment] 2024-07-21 07:37
Duplicate of #17

**Closed** 2024-08-03 10:48 UTC
Labels: duplicate
